import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from typing import Dict, List
import re

class CodeSummarizer:
    def __init__(self, model_name: str = "deepseek-ai/deepseek-coder-1.3b-instruct", device_map: str = "auto"):
        print(f"Loading model {model_name}...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            device_map=device_map,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            trust_remote_code=True
        )
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        print("Model loaded successfully.")

    def build_prompt(self, code_context: str, bug_warnings: List[str]) -> str:
        bugs_section = "\n".join(f"- {w}" for w in bug_warnings) if bug_warnings else "None detected."
        prompt = f"""You are an expert code reviewer. Analyze the code and fill out the report template below. DO NOT repeat or print the original code.

### Code to Analyze:
{code_context[:2000]}

### Static Analysis Bugs:
{bugs_section}

### Fill this exact template:
NORMAL SUMMARY:
[Write 1 technical sentence describing the code here]

BEGINNER EXPLANATION:
[Write a simple step-by-step explanation here]

BUG WARNING:
[Write any bugs found, or 'No obvious bugs' here]

CROSS-FILE CONTEXT:
[List any imports or related files here]

### Response:
NORMAL SUMMARY:
"""
        return prompt

    def summarize_function(self, code_context: str, bug_warnings: List[str]) -> Dict[str, str]:
        prompt = self.build_prompt(code_context, bug_warnings)
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=300,
                do_sample=False,
                pad_token_id=self.tokenizer.eos_token_id,
                eos_token_id=self.tokenizer.eos_token_id
            )
        
        raw_response = self.tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
        raw_response = raw_response.replace("Ġ", " ").replace("Ċ", "\n").replace("ĉ", "\n").replace("âĢĻ", "'").replace("âĢ", '"')
        raw_response = "NORMAL SUMMARY:\n" + raw_response.strip()

        sections = {
            "normal_summary": "",
            "beginner_explanation": "",
            "bug_warning": "",
            "cross_file_context": ""
        }

        # Updated Regex Patterns (Spaces ko handle karne ke liye)
        patterns = {
            "normal_summary": r"NORMAL\s*SUMMARY\s*:?(.*?)(?=(?:BEGINNER\s*EXPLANATION)|(?:BUG\s*WARNING)|(?:CROSS[\-\s]*FILE\s*CONTEXT)|$)",
            "beginner_explanation": r"BEGINNER\s*EXPLANATION\s*:?(.*?)(?=(?:BUG\s*WARNING)|(?:CROSS[\-\s]*FILE\s*CONTEXT)|$)",
            "bug_warning": r"BUG\s*WARNING\s*:?(.*?)(?=(?:CROSS[\-\s]*FILE\s*CONTEXT)|$)",
            "cross_file_context": r"CROSS[\-\s]*FILE\s*CONTEXT\s*:?(.*?)$"
        }

        for key, pattern in patterns.items():
            match = re.search(pattern, raw_response, re.DOTALL | re.IGNORECASE)
            if match:
                cleaned_text = match.group(1).strip()
                cleaned_text = re.sub(r'^[#*\-\s]+', '', cleaned_text)
                sections[key] = cleaned_text if cleaned_text else "[No detailed info generated by model]"
            else:
                sections[key] = "[No detailed info generated by model]"

        return sections